Updates based on usage in production environment

diff --git a/roles/ansible_control_host/files/ssh_shell b/roles/ansible_control_host/files/ssh_shell
--- a/roles/ansible_control_host/files/ssh_shell
+++ b/roles/ansible_control_host/files/ssh_shell
@@ -20,12 +20,12 @@ case $cmd in
         dir=${args[1]}
         if [ $count -ne 2 ]; then
             echo "mkdir: invalid command: wrong number of parameters" >&2
-	    exit 1
+            exit 1
         fi
         echo "$dir" | grep '^tmp/[A-Za-z0-9][A-Za-z0-9]*$' >/dev/null 2>&1
-	if [ $? -ne 0 ]; then
+        if [ $? -ne 0 ]; then
             echo "mkdir: cannot create directory \`$dir': Permission denied" >&2
-	    exit 1
+            exit 1
         fi
         ;;
     scp) 
@@ -33,42 +33,44 @@ case $cmd in
         dir=${args[2]}
         if [ $count -ne 3 ]; then
             echo "scp: invalid command: wrong number of parameters" >&2
-	    exit 1
+            exit 1
         fi
-	if [ $opt != '-t' ]; then
+        if [ $opt != '-t' ]; then
             echo "scp: invalid command: invalid options" >&2
-	    exit 1
+            exit 1
         fi
         echo "$dir" | egrep '^tmp/[A-Za-z0-9]+$|^sysconfig/[A-Za-z0-9]+/[A-Za-z0-9]+$' >/dev/null 2>&1
-	if [ $? -ne 0 ]; then
-	    # allow copies to 1 dir under tmp or 2 dirs under sysconfig - from the home directory
+        if [ $? -ne 0 ]; then
+            # allow copies to 1 dir under tmp or 2 dirs under sysconfig - from the home directory
             echo "scp: cannot create directory \`$dir': Permission denied" >&2
-	    exit 1
+            exit 1
         fi
         if [ ! -d $dir ]; then
-	    echo "scp: cannot stat \`$dir': No such file or directory" >&2
-	    exit 1
+            echo "scp: cannot stat \`$dir': No such file or directory" >&2
+            exit 1
         fi
         ;;
     ansible/bin/ansible_deploy_pkg)
         if [ $count -ne 4 ]; then
             echo "$cmd: invalid command: wrong number of parameters" >&2
-	    exit 1
+            exit 1
         fi
         if [ ! -x $cmd ]; then
             echo "$cmd: cannot execute: No such file or directory" >&2
-	    exit 1
+            exit 1
         fi
         ;;
     ansible/*/*/run)
-        if [ $count -ne 1 ]; then
+        if [ "${args[1]}" = "--tags" -a "${args[2]}" = "aem_packages_sync,aem_sysconfig" ]; then
+            : # parameters ok
+        elif [ $count -ne 1 ]; then
             echo "$cmd: invalid command: wrong number of parameters" >&2
-	    exit 1
+            exit 1
         fi
         echo "$cmd" | grep '^ansible/[A-Za-z0-9][A-Za-z0-9]*/[A-Za-z0-9][A-Za-z0-9]*/run$' >/dev/null 2>&1
-	if [ $? -ne 0 ]; then
-	    echo "$cmd: invalid command" >&2
-	    exit 1
+        if [ $? -ne 0 ]; then
+            echo "$cmd: invalid command" >&2
+            exit 1
         fi
         if [ ! -x $cmd ]; then
             echo "$cmd: cannot execute: No such file or directory" >&2
@@ -78,19 +80,19 @@ case $cmd in
     sysconfig-clean)
         platform=${args[1]}
         env=${args[2]}
-	if [ $count -ne 3 ]; then
-	    echo "$cmd: invalid command: wrong number of parameters" >&2
-	    exit 1
-	fi
-        echo "$platform" | egrep 'tme|sky|nrl' >/dev/null 2>&1
-	if [ $? -ne 0 ]; then
-	    echo "sysconfig-clean: platform must be tme or nrl or sky" >&2
-	    exit 1
+        if [ $count -ne 3 ]; then
+            echo "$cmd: invalid command: wrong number of parameters" >&2
+            exit 1
+        fi
+        echo "$platform" | egrep 'tme|sky|nrl|puck' >/dev/null 2>&1
+        if [ $? -ne 0 ]; then
+            echo "sysconfig-clean: platform must be tme or nrl or sky" >&2
+            exit 1
         fi
         echo "$env" | egrep 'dev|uat|prod' >/dev/null 2>&1
-	if [ $? -ne 0 ]; then
-	    echo "sysconfig-clean: env must have dev or uat or prod in it" >&2
-	    exit 1
+        if [ $? -ne 0 ]; then
+            echo "sysconfig-clean: env must have dev or uat or prod in it" >&2
+            exit 1
         fi
 
         mkdir -p sysconfig/${platform}/${env}
@@ -102,7 +104,7 @@ case $cmd in
         ;;
     *)
         echo "$cmd: cannot execute: No such file or directory"
-	exit 1
+        exit 1
 esac
 
 exec $SSH_ORIGINAL_COMMAND
